baseurl = ""
relativeurls = true

languageCode = "en-us"
title = "Tamás Gál"
disqusShortname = "tmsgl"

pygmentsUseClasses = true
pygmentsCodeFences = true 

[permalinks]
    blog = "/:filename/"

[taxonomies]
    tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
    homeText = "You just made Hugo from scratch."
    dateFormat = "2006-01-02"
